# columns.py

COLUMNS = [
    "Unique ID", "Product Name - en-US",
    "Sellable Part Number", "Base Part Number",
    "18 Set - Bullet 01 - en-CA", "18 Set - Bullet 01 - en-US",
    "18 Set - Bullet 02 - en-CA", "18 Set - Bullet 02 - en-US",
    "18 Set - Bullet 03 - en-CA", "18 Set - Bullet 03 - en-US",
    "18 Set - Bullet 04 - en-CA", "18 Set - Bullet 04 - en-US",
    "18 Set - Bullet 05 - en-CA", "18 Set - Bullet 05 - en-US",
    "18 Set - Bullet 06 - en-CA", "18 Set - Bullet 06 - en-US",
    "18 Set - Bullet 07 - en-CA", "18 Set - Bullet 07 - en-US",
    "18 Set - Bullet 08 - en-CA", "18 Set - Bullet 08 - en-US",
    "18 Set - Bullet 09 - en-CA", "18 Set - Bullet 09 - en-US",
    "18 Set - Bullet 10 - en-CA", "18 Set - Bullet 10 - en-US",
    "18 Set - Bullet 11 - en-CA", "18 Set - Bullet 11 - en-US",
    "18 Set - Bullet 12 - en-CA", "18 Set - Bullet 12 - en-US",
    "18 Set - Bullet 13 - en-CA", "18 Set - Bullet 13 - en-US",
    "18 Set - Bullet 14 - en-CA", "18 Set - Bullet 14 - en-US",
    "18 Set - Bullet 15 - en-CA", "18 Set - Bullet 15 - en-US",
    "18 Set - Bullet 16 - en-CA", "18 Set - Bullet 16 - en-US",
    "18 Set - Bullet 17 - en-CA", "18 Set - Bullet 17 - en-US",
    "18 set - Bullet 18 - en-CA", "18 set - Bullet 18 - en-US",
    "3 Set - Bullet 01 - en-CA", "3 Set - Bullet 01 - en-US",
    "3 Set - Bullet 02 - en-CA", "3 Set - Bullet 02 - en-US",
    "3 Set - Bullet 03 - en-CA", "3 Set - Bullet 03 - en-US",
    "5 Set - Bullet 01 - en-CA", "5 Set - Bullet 01 - en-US",
    "5 Set - Bullet 02 - en-CA", "5 Set - Bullet 02 - en-US",
    "5 Set - Bullet 03 - en-CA", "5 Set - Bullet 03 - en-US",
    "5 Set - Bullet 04 - en-CA", "5 Set - Bullet 04 - en-US",
    "5 Set - Bullet 05 - en-CA", "5 Set - Bullet 05 - en-US",
    "9 Set - Bullet 01 - en-CA", "9 Set - Bullet 01 - en-US",
    "9 Set - Bullet 02 - en-CA", "9 Set - Bullet 02 - en-US",
    "9 Set - Bullet 03 - en-CA", "9 Set - Bullet 03 - en-US",
    "9 Set - Bullet 04 - en-CA", "9 Set - Bullet 04 - en-US",
    "9 Set - Bullet 05 - en-CA", "9 Set - Bullet 05 - en-US",
    "9 Set - Bullet 06 - en-CA", "9 Set - Bullet 06 - en-US",
    "9 Set - Bullet 07 - en-CA", "9 Set - Bullet 07 - en-US",
    "9 Set - Bullet 08 - en-CA", "9 Set - Bullet 08 - en-US",
    "9 Set - Bullet 09 - en-CA", "9 Set - Bullet 09 - en-US",
    "Marketing Copy Paragraph - en-CA", "Marketing Copy Paragraph - en-US",
    "Salient Bullet 01 - en-US", "Salient Bullet 02 - en-US", "Salient Bullet 03 - en-US",
    "SEO Keywords", "Warranty Sheet - en-US",
    "Alternative Image 01", "Alternative Image 01 (with Logo)",
    "Alternative Image 02", "Alternative Image 02 (with Logo)",
    "Alternative Image 03", "Alternative Image 03 (with Logo)",
    "Alternative Image 04", "Alternative Image 04 (with Logo)",
    "Alternative Image 05", "Alternative Image 05 (with Logo)",
    "Alternative Image 06", "Alternative Image 06 (with Logo)",
    "Crop Image", "Dimensional Image", "Lifestyle Image", "Lifestyle Image (with Logo)",
    "EC Module 1 Image 1", "EC Module 1 Image 1 Alt Text", "EC Module 1 Image 1 Header", "EC Module 1 Image 1 Paragraph",
    "EC Module 1 Image 2", "EC Module 1 Image 2 Alt Text", "EC Module 1 Image 2 Header", "EC Module 1 Image 2 Paragraph",
    "EC Module 1 Image 3", "EC Module 1 Image 3 Alt Text", "EC Module 1 Image 3 Header", "EC Module 1 Image 3 Paragraph",
    "EC Module 1 Image 4", "EC Module 1 Image 4 Alt Text", "EC Module 1 Image 4 Header", "EC Module 1 Image 4 Paragraph",
    "EC Module 2 Image 1", "EC Module 2 Image 1 Alt Text", "EC Module 2 Image 1 Header", "EC Module 2 Image 1 Paragraph",
    "EC Module 2 Image 2", "EC Module 2 Image 2 Alt Text", "EC Module 2 Image 2 Header", "EC Module 2 Image 2 Paragraph",
    "EC Module 2 Image 3", "EC Module 2 Image 3 Alt Text", "EC Module 2 Image 3 Header", "EC Module 2 Image 3 Paragraph",
    "EC Module 2 Image 4", "EC Module 2 Image 4 Alt Text", "EC Module 2 Image 4 Header", "EC Module 2 Image 4 Paragraph",
    "Bullet Points - en-CA", "Bullet Points - en-US"
]
